apiVersion: v1
kind: Namespace
metadata:
  name: vm-assessment
  labels:
    name: vm-assessment
    app.kubernetes.io/name: vm-assessment-bom
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vm-assessment-quota
  namespace: vm-assessment
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "2"
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: vm-assessment-limits
  namespace: vm-assessment
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container