name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  # Fast validation for PRs
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Basic syntax check
      run: |
        python -m py_compile web_app/app.py

    - name: Validate configuration
      run: |
        python -c "import json; json.load(open('web_app/pricing.json'))"

    - name: Validate container build
      run: |
        docker build -f Containerfile -t test-build .

    - name: Test container startup
      run: |
        # Start container in background
        docker run -d --name test-app -p 8000:8000 test-build
        
        # Wait for startup
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8000/ || exit 1
        
        # Cleanup
        docker stop test-app
        docker rm test-app

  # Size and security check
  size-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build image for size check
      run: |
        docker build -f Containerfile -t size-check .

    - name: Check image size
      run: |
        SIZE=$(docker images size-check --format "{{.Size}}")
        echo "Image size: $SIZE"
        
        # Convert to MB for comparison (rough calculation)
        SIZE_MB=$(docker images size-check --format "{{.Size}}" | sed 's/MB//' | sed 's/GB/*1000/' | bc -l 2>/dev/null || echo 1000)
        
        if (( $(echo "$SIZE_MB > 1000" | bc -l) )); then
          echo "Warning: Image size is larger than 1GB"
        fi

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'size-check'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'